#!/bin/bash
date
echo "uptime:"
uptime 
echo "Currently connected:"
w 
echo "-------------------------------------"
echo "Last logins:"
last  -F | head -4
echo "-------------------------------------"
echo "Open TCP ports:"
nmap -F 192.168.1.1
