#!/bin/bash
date
echo "uptime:"
uptime 
echo "Memory and Swap"
free -h
echo "Currently connected:"
w 
echo "-------------------------------------"
echo "Last logins:"
last  -F | head -4
echo "-------------------------------------"
echo "Open ports:"
echo "uncomment and replace IP "
#nmap -F 192.168.1.1
echo "-------------------------------------"
echo "Current connections:"
ss -s 
echo "-------------------------------------"
echo "processes"
echo "Uncomment based on need"
#ps -eF 
echo "-------------------------------------"
echo "Richer processes"
ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head
