name: MyMainGitHub

on: 
  push:
    branches: 
      - master


jobs:
  my_testing:

    runs-on: macos
    name: Test on Macos
    steps:
      - run: pip3 install awscli --upgrade --user
      - run: aws --version  
  
        
      
        
        
    

        
        
        
  my_testing2:
    runs-on: ubuntu-latest
    name: Test on Ubundu
    steps:
      - run: aws --version
