name: MyMainGitHub

on: 
  push:
    branches: 
      - master


jobs:
  my_testing:

    runs-on: [macos-latest]
    name: Test on Macos
    steps:
      - run: aws --version
    

        
        
        
  my_testing2:
    runs-on: [ubuntu-latest]
    steps:
      - 
