name: MyMainGitHub

on: 
  push:
    branches: 
      - master


jobs:
  my_testing:

    runs-on: macos
    name: Test on Macos
    steps:
      - run: aws --version
    

        
        
        
  my_testing2:
    runs-on: ubuntu-latest
    name: Test on Ubundu
    steps:
      - run: aws --version
